/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AlizeSpkRec_SimpleSpkDetSystem */

#ifndef _Included_AlizeSpkRec_SimpleSpkDetSystem
#define _Included_AlizeSpkRec_SimpleSpkDetSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    featureCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_featureCount
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    speakerCount
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_speakerCount
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    isUBMLoaded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_isUBMLoaded
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    speakerIDs
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_speakerIDs
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    setOption
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_setOption
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    decisionThreshold
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_decisionThreshold
        (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    setDecisionThreshold
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_setDecisionThreshold
        (JNIEnv *, jobject, jdouble);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    addAudio
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_addAudio___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    addAudio
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_addAudio___3S
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    addAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_addAudio__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    saveAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_saveAudio
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    resetAudio
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_resetAudio
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    addFeatures
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_addFeatures___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    addFeatures
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_addFeatures__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    saveFeatures
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_saveFeatures
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    resetFeatures
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_resetFeatures
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    loadBackgroundModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_loadBackgroundModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    loadSpeakerModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_loadSpeakerModel
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    saveSpeakerModel
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_saveSpeakerModel
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    removeSpeaker
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_removeSpeaker
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    removeAllSpeakers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_removeAllSpeakers
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    createSpeakerModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_createSpeakerModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    adaptSpeakerModel
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_adaptSpeakerModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    verifySpeaker
 * Signature: (Ljava/lang/String;Z)LAlizeSpkRec/SimpleSpkDetSystem/SpkRecResult;
 */
JNIEXPORT jobject JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_verifySpeaker
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    identifySpeaker
 * Signature: (Z)LAlizeSpkRec/SimpleSpkDetSystem/SpkRecResult;
 */
JNIEXPORT jobject JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_identifySpeaker
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    resetAccumulatedScore
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_resetAccumulatedScore
  (JNIEnv *, jobject, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    resetAllAccumulatedScores
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_resetAllAccumulatedScores
  (JNIEnv *, jobject);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    initSystem
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_initSystem
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     AlizeSpkRec_SimpleSpkDetSystem
 * Method:    releaseSystem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AlizeSpkRec_SimpleSpkDetSystem_releaseSystem
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
